package com.example.soap;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRegistry;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.soap.SOAPBody;
import jakarta.xml.soap.SOAPMessage;
import jakarta.xml.ws.handler.MessageContext;
import jakarta.xml.ws.handler.soap.SOAPHandler;
import jakarta.xml.ws.handler.soap.SOAPMessageContext;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.lang.reflect.ParameterizedType;
import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.xml.namespace.QName;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;

/**
 * JAX-WS SOAP Handler that filters out unknown elements from responses.
 * This allows the client to handle responses with additional fields
 * not defined in the local WSDL schema.
 *
 * Known fields are automatically detected from JAXB-generated classes
 * by scanning the ObjectFactory class.
 */
public class UnknownElementFilter implements SOAPHandler<SOAPMessageContext> {

    // Cache of known fields per XML type name
    private final Map<String, Set<String>> knownFieldsCache = new HashMap<>();

    /**
     * Create filter by scanning the ObjectFactory class for JAXB types.
     * ObjectFactory is automatically generated by CXF from WSDL.
     *
     * @param objectFactoryClass the ObjectFactory class from generated package
     */
    public UnknownElementFilter(Class<?> objectFactoryClass) {
        if (objectFactoryClass == null) {
            throw new IllegalArgumentException("ObjectFactory class must not be null");
        }
        if (!objectFactoryClass.isAnnotationPresent(XmlRegistry.class)) {
            throw new IllegalArgumentException("Class must be annotated with @XmlRegistry");
        }
        scanObjectFactory(objectFactoryClass);
    }

    /**
     * Scan ObjectFactory to discover all JAXB-generated classes.
     */
    private void scanObjectFactory(Class<?> objectFactoryClass) {
        for (Method method : objectFactoryClass.getDeclaredMethods()) {
            // Look for create*() methods that return JAXB types
            if (method.getName().startsWith("create") && method.getParameterCount() == 0) {
                Class<?> returnType = method.getReturnType();
                if (returnType.isAnnotationPresent(XmlType.class)) {
                    registerJaxbClass(returnType);
                }
            }
            // Also check create*(T value) methods that return JAXBElement<T>
            if (method.getName().startsWith("create") && method.getParameterCount() == 1) {
                Type genericReturnType = method.getGenericReturnType();
                if (genericReturnType instanceof ParameterizedType) {
                    ParameterizedType pt = (ParameterizedType) genericReturnType;
                    if (pt.getRawType() == JAXBElement.class) {
                        Type[] typeArgs = pt.getActualTypeArguments();
                        if (typeArgs.length > 0 && typeArgs[0] instanceof Class) {
                            Class<?> jaxbClass = (Class<?>) typeArgs[0];
                            if (jaxbClass.isAnnotationPresent(XmlType.class)) {
                                registerJaxbClass(jaxbClass);
                            }
                        }
                    }
                }
            }
        }
    }

    /**
     * Register a JAXB class and extract its known field names from annotations.
     */
    private void registerJaxbClass(Class<?> clazz) {
        if (knownFieldsCache.containsKey(getTypeName(clazz))) {
            return; // Already registered
        }

        Set<String> fields = new HashSet<>();

        // Extract field names from @XmlElement annotations
        for (Field field : clazz.getDeclaredFields()) {
            XmlElement xmlElement = field.getAnnotation(XmlElement.class);
            if (xmlElement != null) {
                String name = xmlElement.name();
                if ("##default".equals(name)) {
                    name = field.getName();
                }
                fields.add(name);
            } else {
                // Field without @XmlElement uses its Java name
                fields.add(field.getName());
            }
        }

        String typeName = getTypeName(clazz);
        knownFieldsCache.put(typeName, fields);
    }

    private String getTypeName(Class<?> clazz) {
        XmlType xmlType = clazz.getAnnotation(XmlType.class);
        return (xmlType != null && !xmlType.name().isEmpty())
            ? xmlType.name()
            : clazz.getSimpleName();
    }

    @Override
    public Set<QName> getHeaders() {
        return null;
    }

    @Override
    public boolean handleMessage(SOAPMessageContext context) {
        Boolean outbound = (Boolean) context.get(MessageContext.MESSAGE_OUTBOUND_PROPERTY);

        // Only process inbound (response) messages
        if (outbound != null && !outbound) {
            filterUnknownElements(context);
        }

        return true;
    }

    @Override
    public boolean handleFault(SOAPMessageContext context) {
        return true;
    }

    @Override
    public void close(MessageContext context) {
    }

    private void filterUnknownElements(SOAPMessageContext context) {
        try {
            SOAPMessage message = context.getMessage();
            if (message == null) {
                return;
            }

            SOAPBody body = message.getSOAPBody();
            if (body == null) {
                return;
            }

            // Find elements matching known types and filter unknown children
            filterElements(body);

            // Save changes
            message.saveChanges();

        } catch (Exception e) {
            System.err.println("Error filtering unknown elements: " + e.getMessage());
        }
    }

    private void filterElements(Node node) {
        NodeList children = node.getChildNodes();

        for (int i = 0; i < children.getLength(); i++) {
            Node child = children.item(i);

            if (child.getNodeType() == Node.ELEMENT_NODE) {
                Element element = (Element) child;

                // Check if this element matches a known type and filter unknown children
                String matchedType = detectKnownType(element);
                if (matchedType != null) {
                    removeUnknownFields(element, knownFieldsCache.get(matchedType));
                }

                // Recursively process children
                filterElements(child);
            }
        }
    }

    /**
     * Detect if the element contains fields matching a registered JAXB type.
     * Returns the type name if matched, null otherwise.
     *
     * Matching strategy: Find a type whose ALL known fields are present in child elements,
     * and prefer the type with the most matching fields. This allows filtering out
     * extra fields added by the provider while correctly identifying the target type.
     *
     * Example: If child elements are {userId, name, status, created, attribute}
     * - getUserInfo has {userId} -> matches but only 1 field
     * - User has {userId, name, status, created} -> matches with 4 fields (best match)
     * Result: User is selected, and 'attribute' will be filtered out.
     */
    private String detectKnownType(Element element) {
        NodeList children = element.getChildNodes();
        Set<String> childNames = new HashSet<>();

        for (int i = 0; i < children.getLength(); i++) {
            Node child = children.item(i);
            if (child.getNodeType() == Node.ELEMENT_NODE) {
                childNames.add(child.getLocalName());
            }
        }

        if (childNames.isEmpty()) {
            return null;
        }

        // Find the best matching type:
        // - All known fields must be present in child elements
        // - Prefer the type with the most matching fields
        String bestMatch = null;
        int bestMatchCount = 0;

        for (Map.Entry<String, Set<String>> entry : knownFieldsCache.entrySet()) {
            Set<String> knownFields = entry.getValue();

            // Check if all known fields are present in child elements
            // This allows extra fields in response that will be filtered out
            if (childNames.containsAll(knownFields)) {
                int matchCount = knownFields.size();
                if (matchCount > bestMatchCount) {
                    bestMatchCount = matchCount;
                    bestMatch = entry.getKey();
                }
            }
        }

        return bestMatch;
    }

    private void removeUnknownFields(Element element, Set<String> knownFields) {
        NodeList children = element.getChildNodes();
        List<Node> toRemove = new ArrayList<>();

        for (int i = 0; i < children.getLength(); i++) {
            Node child = children.item(i);
            if (child.getNodeType() == Node.ELEMENT_NODE) {
                String name = child.getLocalName();
                if (!knownFields.contains(name)) {
                    toRemove.add(child);
                }
            }
        }

        for (Node node : toRemove) {
            element.removeChild(node);
        }
    }
}
